---
line_ending: lf

formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  max_line_length: 150
  pad_line_comments: 1
  trim_trailing_whitespace: true
  eof_newline: true
