version: '3'

tasks:

  format:
    desc: Run 'goimports' to format go imports
    summary: Runs goimports on all files with -local support, can also replace gofmt
    cmds:
      - goimports -local github.com/vallieres/mx-creative-console-ccbm -w .
      - go mod tidy
      - gofumpt -l -w .
      - shfmt -w .

  lint:
    desc: Code Linting
    summary: Lint the project files with golangci-lint
    cmds:
      - golangci-lint run --fix -c .golangci.yml

  test:
    desc: Run the tests
    summary: Runs the tests
    cmds:
      - gotestsum ./... -race -count=1 -p 1 -coverprofile=coverage.out -coverpkg=./...
      - go tool cover -html=coverage.out -o coverage.html
